// src/lib/Button.svelte
<script lang="ts">
	export let type: 'submit' | 'reset' | 'button' | undefined = 'button';
	export const click = () => button.click();
	let button: HTMLButtonElement;
</script>

<button on:click bind:this={button} {type}><slot /></button>

<style lang="postcss">
	button {
		@apply text-cyan-500 text-lg font-bold border-2 border-cyan-500 rounded-md shadow-md active:shadow-none active:translate-y-[1px] px-4 py-2;
	}
</style>

// components/Button.tsx
import classNames from "classnames";
import React, { FC } from "react";

interface Props {
  primary?: boolean;
  type?: "button" | "submit" | "reset";
  onClick?: React.MouseEventHandler<HTMLButtonElement>;
}

export const Button: FC<Props> = (props) => {
  return (
    <button
      type={props.type ?? "button"}
      className={classNames(
        " py-2 px-4 shadow-md border-2 rounded-md text-white font-semibold active:translate-y-[1px] active:shadow-none",
        {
          "bg-orange-500": props.primary,
        }
      )}
      onClick={props.onClick}
    >
      {props.children}
    </button>
  );
};

export default Button;
